@baseUrl=http://localhost:8080
###
@email=asvelezer@gmail.com
###
GET {{baseUrl}}/api/v1/auth/verification?email={{email}} HTTP/1.1
###
POST {{baseUrl}}/api/v1/auth/signUp HTTP/1.1
Content-Type: application/json

{
    "name": "arief",
    "phoneNumber": "+6283842455250",
    "email": "asvelezer@gmail.com",
    "password": "password",
    "creditCardNumber":"13823982",
    "cvv":"123",
    "expiredDate":"09/2025",
    "cardHolderName":"arief"
}
###
POST {{baseUrl}}/api/v1/otp HTTP/1.1
Content-Type: application/json

{
    "email": "{{email}}",
    "type": "VERIFY_EMAIL"
}
###
@otpIdVerif=7b7aae1c-df36-4073-99b9-9be13ced9fbb
@otpValueVerif=4605
###
PUT {{baseUrl}}/api/v1/auth/verification HTTP/1.1
Content-Type: application/json

{
    "email": "{{email}}",
    "otpId": "{{otpIdVerif}}",
    "otpValue": "{{otpValueVerif}}"
}
###
GET {{baseUrl}}/api/v1/auth/verification?email={{email}} HTTP/1.1
###
POST {{baseUrl}}/api/v1/auth/signIn HTTP/1.1
Content-Type: application/json

{
    "email": "{{email}}",
    "password": "password"
}
###
POST {{baseUrl}}/api/v1/auth/refresh HTTP/1.1
Content-Type: application/json

{
  "accessToken": "eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFzdmVsZXplckBnbWFpbC5jb20iLCJpZCI6IjY3ODg1NTc5LWE5ZDYtNDEzYy04NjI4LTIyNTAzZDFhNjIxZSIsInN1YiI6ImFzdmVsZXplckBnbWFpbC5jb20iLCJpYXQiOjE3MDY2MTcxMjEsImV4cCI6MTcwNjYxODkyMX0.s6jL1jGiq89YxilzYoRv2pf_MnXtNJyB_mCYU_jBs1s",
  "refreshToken": "eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFzdmVsZXplckBnbWFpbC5jb20iLCJpZCI6IjY3ODg1NTc5LWE5ZDYtNDEzYy04NjI4LTIyNTAzZDFhNjIxZSIsInN1YiI6ImV5SmhiR2NpT2lKSVV6STFOaUo5LmV5SmxiV0ZwYkNJNkltRnpkbVZzWlhwbGNrQm5iV0ZwYkM1amIyMGlMQ0pwWkNJNklqWTNPRGcxTlRjNUxXRTVaRFl0TkRFell5MDROakk0TFRJeU5UQXpaREZoTmpJeFpTSXNJbk4xWWlJNkltRnpkbVZzWlhwbGNrQm5iV0ZwYkM1amIyMGlMQ0pwWVhRaU9qRTNNRFkyTVRjeE1qRXNJbVY0Y0NJNk1UY3dOall4T0RreU1YMC5zNmpMMWpHaXE4OVl4aWx6WW9SdjJwZl9Nblh0Tkp5Ql9tQ1lVX2pCczFzIiwiaWF0IjoxNzA2NjE3MTIxLCJleHAiOjE3MDY2MTg5MjF9.KMm0LJNJ4TPONvkQYw-RPRRRciKhF-4PkbvMXTCxRo4"
}
###
POST {{baseUrl}}/api/v1/otp HTTP/1.1
Content-Type: application/json

{
    "email": "{{email}}",
    "type": "RESET_PASSWORD"
}
###
@otpIdReset=da44debc-c72c-4b77-ac4b-6424bed81f17
@otpValueReset=2065
###
PATCH {{baseUrl}}/api/v1/auth/reset HTTP/1.1
Content-Type: application/json

{
    "otpId": "{{otpIdReset}}",
    "otpValue": "{{otpValueReset}}",
    "email": "{{email}}",
    "password": "password"
}
###
###

###
@token=eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFzdmVsZXplckBnbWFpbC5jb20iLCJpZCI6IjY3ODg1NTc5LWE5ZDYtNDEzYy04NjI4LTIyNTAzZDFhNjIxZSIsInN1YiI6ImFzdmVsZXplckBnbWFpbC5jb20iLCJpYXQiOjE3MDY2MTcxMjEsImV4cCI6MTcwNjYxODkyMX0.s6jL1jGiq89YxilzYoRv2pf_MnXtNJyB_mCYU_jBs1s
GET {{baseUrl}}/api/v1/user/me HTTP/1.1
Authorization: Bearer {{token}}
###
GET {{baseUrl}}/api/v1/user/me/creditCard HTTP/1.1
Authorization: Bearer {{token}}
###
PUT {{baseUrl}}/api/v1/user/me HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name":"name",
    "password": "password"
}
###
GET {{baseUrl}}/api/v1/product HTTP/1.1
###
GET {{baseUrl}}/api/v1/subscription HTTP/1.1
Authorization: Bearer {{token}}
###
@productId=da44debc-c72c-4b77-ac4b-6424bed81f17
###
POST {{baseUrl}}/api/v1/subscription HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "productId": "{{productId}}"
}
###
GET {{baseUrl}}/api/v1/subscription HTTP/1.1
Authorization: Bearer {{token}}
###
@subscriptionId=b557cacf-a3d3-42ac-9ea9-bded7da4e676
###
PATCH {{baseUrl}}/api/v1/subscription/{{subscriptionId}} HTTP/1.1
Authorization: Bearer {{token}}
###
DELETE {{baseUrl}}/api/v1/subscription/{{subscriptionId}} HTTP/1.1
Authorization: Bearer {{token}}
###
GET {{baseUrl}}/api/v1/payment/transaction/history HTTP/1.1
Authorization: Bearer {{token}}
###
POST {{baseUrl}}/api/v1/payment/transaction/history HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "subscriptionId": "{{subscriptionId}}",
    "creditCardId": "a1116cfb-7ecb-4667-b5b5-5572673db7f9"
}
###
GET {{baseUrl}}/api/v1/payment/transaction/history HTTP/1.1
Authorization: Bearer {{token}}
###
POST {{baseUrl}}/api/v1/otp HTTP/1.1
Content-Type: application/json

{
    "email": "{{email}}",
    "type": "PAYMENT"
}
###
@transactionHistoryId=63de5635-1c4b-4dec-ab33-ded3f9602de4
@otpIdPayment=977da3ff-8c33-48a8-945c-88f2ed5396a8
@otpValuePayment=6267
###
PATCH {{baseUrl}}/api/v1/payment/transaction/history/{{transactionHistoryId}} HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "otpId": "{{otpIdPayment}}",
    "otpValue": "{{otpValuePayment}}"

}
###
GET {{baseUrl}}/api/v1/subscription HTTP/1.1
Authorization: Bearer {{token}}