@baseUrl=http://localhost:8080
###
@email=asvelezer@gmail.com
###
GET {{baseUrl}}/api/v1/auth/verification?email={{email}} HTTP/1.1
###
POST {{baseUrl}}/api/v1/auth/signUp HTTP/1.1
Content-Type: application/json

{
    "name": "arief",
    "phoneNumber": "+6283842455250",
    "email": "asvelezer@gmail.com",
    "password": "password",
    "creditCardNumber":"13823982",
    "cvv":"123",
    "expiredDate":"09/2025",
    "cardHolderName":"arief"
}
###
POST {{baseUrl}}/api/v1/otp HTTP/1.1
Content-Type: application/json

{
    "email": "{{email}}",
    "type": "VERIFY_EMAIL"
}
###
@otpIdVerif=f8a82644-cf12-4513-adcc-97a0a51670da
@otpValueVerif=1149
###
PUT {{baseUrl}}/api/v1/auth/verification HTTP/1.1
Content-Type: application/json

{
    "email": "{{email}}",
    "otpId": "{{otpIdVerif}}",
    "otpValue": "{{otpValueVerif}}"
}
###
GET {{baseUrl}}/api/v1/auth/verification?email={{email}} HTTP/1.1
###
POST {{baseUrl}}/api/v1/auth/signIn HTTP/1.1
Content-Type: application/json

{
    "email": "{{email}}",
    "password": "password"
}
###
POST {{baseUrl}}/api/v1/auth/refresh HTTP/1.1
Content-Type: application/json

{
  "accessToken": "eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjQzMDA2NmU1LTg2ZDItNDI4Yi1iMWFmLWFjZjkyMzE5YjczYSIsImVtYWlsIjoiYXN2ZWxlemVyQGdtYWlsLmNvbSIsInN1YiI6ImFzdmVsZXplckBnbWFpbC5jb20iLCJpYXQiOjE3MDY2NjU2ODQsImV4cCI6MTcwNjY2NzQ4NH0.uh1yoLWYT0xAgCyMxovovdC9sap1Rrvlq1Q6YjEe3OE",
  "refreshToken": "eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjQzMDA2NmU1LTg2ZDItNDI4Yi1iMWFmLWFjZjkyMzE5YjczYSIsImVtYWlsIjoiYXN2ZWxlemVyQGdtYWlsLmNvbSIsInN1YiI6ImV5SmhiR2NpT2lKSVV6STFOaUo5LmV5SnBaQ0k2SWpRek1EQTJObVUxTFRnMlpESXROREk0WWkxaU1XRm1MV0ZqWmpreU16RTVZamN6WVNJc0ltVnRZV2xzSWpvaVlYTjJaV3hsZW1WeVFHZHRZV2xzTG1OdmJTSXNJbk4xWWlJNkltRnpkbVZzWlhwbGNrQm5iV0ZwYkM1amIyMGlMQ0pwWVhRaU9qRTNNRFkyTmpVMk9EUXNJbVY0Y0NJNk1UY3dOalkyTnpRNE5IMC51aDF5b0xXWVQweEFnQ3lNeG92b3ZkQzlzYXAxUnJ2bHExUTZZakVlM09FIiwiaWF0IjoxNzA2NjY1Njg0LCJleHAiOjE3MDY2Njc0ODR9.uHvJFRtl7AwyeAsHe3J1D8-4VeRkmYzNCYPIuR0gcJ0"
}
###
###
POST {{baseUrl}}/api/v1/otp HTTP/1.1
Content-Type: application/json

{
    "email": "{{email}}",
    "type": "RESET_PASSWORD"
}
###
@otpIdReset=dca62030-2106-4884-b909-ef0fe602c3af
@otpValueReset=2741
###
PATCH {{baseUrl}}/api/v1/auth/reset HTTP/1.1
Content-Type: application/json

{
    "otpId": "{{otpIdReset}}",
    "otpValue": "{{otpValueReset}}",
    "email": "{{email}}",
    "password": "password"
}
###
###
@token=eyJhbGciOiJIUzI1NiJ9.eyJpZCI6ImNiOTYyZGNiLWNiZTktNGJmNy05MDdlLTZkMTIwN2YzMzFiMyIsImVtYWlsIjoiYXN2ZWxlemVyQGdtYWlsLmNvbSIsInN1YiI6ImFzdmVsZXplckBnbWFpbC5jb20iLCJpYXQiOjE3MDY2Njg2NjYsImV4cCI6MTcwNjY3MDQ2Nn0.dqJD5ABw5I7Ylj5_CWQopSw6U9jDjZNSgzQ57JLUHH4
###
GET {{baseUrl}}/api/v1/user/me HTTP/1.1
Authorization: Bearer {{token}}
###
GET {{baseUrl}}/api/v1/user/me/creditCard HTTP/1.1
Authorization: Bearer {{token}}
###
PUT {{baseUrl}}/api/v1/user/me HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name":"name",
    "password": "password"
}
###
GET {{baseUrl}}/api/v1/product HTTP/1.1
###
GET {{baseUrl}}/api/v1/subscription HTTP/1.1
Authorization: Bearer {{token}}
###
@productId=da44debc-c72c-4b77-ac4b-6424bed81f17
# @productId=cb55debc-c72c-4b77-ac4b-6424bed81f11
###
POST {{baseUrl}}/api/v1/subscription HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "productId": "{{productId}}"
}
###
GET {{baseUrl}}/api/v1/subscription HTTP/1.1
Authorization: Bearer {{token}}
###
@subscriptionId=ad77cacf-a769-48a2-94aa-e4af77d9bcf0
###
PATCH {{baseUrl}}/api/v1/subscription/{{subscriptionId}} HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "qty": 5
}
###
DELETE {{baseUrl}}/api/v1/subscription/{{subscriptionId}} HTTP/1.1
Authorization: Bearer {{token}}
### 
GET {{baseUrl}}/api/v1/payment/transaction/history HTTP/1.1
Authorization: Bearer {{token}}
###
GET {{baseUrl}}/api/v1/user/me/creditCard HTTP/1.1
Authorization: Bearer {{token}}
###
@creditCardId=4d79ef75-c237-404d-a59b-4c02d3263ea3
### create payment
POST {{baseUrl}}/api/v1/payment/transaction/history HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "subscriptionId": "{{subscriptionId}}",
    "creditCardId": "{{creditCardId}}",
    "creditCardNumber":"13823982",
    "cvv":"123",
    "expiredDate":"09/2025",
    "cardHolderName":"arief"
}
###
GET {{baseUrl}}/api/v1/payment/transaction/history HTTP/1.1
Authorization: Bearer {{token}}
###
POST {{baseUrl}}/api/v1/otp HTTP/1.1
Content-Type: application/json

{
    "email": "{{email}}",
    "type": "PAYMENT"
}
###
@transactionHistoryId=506a32b4-cc7a-4f84-9874-b8b1dcc6334d
@otpIdPayment=c1f7b494-2f3d-441e-946a-290c5a7174fb
@otpValuePayment=5303
###
PATCH {{baseUrl}}/api/v1/payment/transaction/history/{{transactionHistoryId}} HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "otpId": "{{otpIdPayment}}",
    "otpValue": "{{otpValuePayment}}",
    "amount": 3000000
}
###
GET {{baseUrl}}/api/v1/subscription HTTP/1.1
Authorization: Bearer {{token}}
###
POST http://localhost:8082/api/v1/mock/payment/r3 HTTP/1.1
Content-Type: application/json

{"random":{"random":"random"}}