version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_HOSTNAME: postgres
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  spring-boot-app:
    image: spring-boot-app:latest
    depends_on:
      - postgres
    ports:
      - "8080:8080"
