@baseUrl=http://localhost:8080
###
@email=asvelezer@gmail.com
###
GET {{baseUrl}}/api/v1/auth/verification?email={{email}} HTTP/1.1
###
POST {{baseUrl}}/api/v1/auth/signUp HTTP/1.1
Content-Type: application/json

{
    "name": "arief",
    "phoneNumber": "+6283842455250",
    "email": "asvelezer@gmail.com",
    "password": "password",
    "creditCardNumber":"13823982",
    "cvv":"123",
    "expiredDate":"09/2025",
    "cardHolderName":"arief"
}
###
POST {{baseUrl}}/api/v1/otp HTTP/1.1
Content-Type: application/json

{
    "email": "{{email}}",
    "type": "VERIFY_EMAIL"
}
###
@otpIdVerif=28cb2a0a-38c6-4d77-9854-d0ef4aff8b2b
@otpValueVerif=7371
###
PUT {{baseUrl}}/api/v1/auth/verification HTTP/1.1
Content-Type: application/json

{
    "email": "{{email}}",
    "otpId": "{{otpIdVerif}}",
    "otpValue": "{{otpValueVerif}}"
}
###
GET {{baseUrl}}/api/v1/auth/verification?email={{email}} HTTP/1.1
###
POST {{baseUrl}}/api/v1/auth/signIn HTTP/1.1
Content-Type: application/json

{
    "email": "{{email}}",
    "password": "password"
}
###
POST {{baseUrl}}/api/v1/auth/refresh HTTP/1.1
Content-Type: application/json

{
  "accessToken": "eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFzdmVsZXplckBnbWFpbC5jb20iLCJpZCI6ImZkMjdjMmE0LWM1MTEtNDkwMC1hNjcyLThjNTM1MTI2YjgzYSIsInN1YiI6ImFzdmVsZXplckBnbWFpbC5jb20iLCJpYXQiOjE3MDY2MzMxNjIsImV4cCI6MTcwNjYzNDk2Mn0.IqW70lRYt1SyuMnxN-dbyJ0vKzntAM3qzsaDJRMToKs",
  "refreshToken": "eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFzdmVsZXplckBnbWFpbC5jb20iLCJpZCI6ImZkMjdjMmE0LWM1MTEtNDkwMC1hNjcyLThjNTM1MTI2YjgzYSIsInN1YiI6ImV5SmhiR2NpT2lKSVV6STFOaUo5LmV5SmxiV0ZwYkNJNkltRnpkbVZzWlhwbGNrQm5iV0ZwYkM1amIyMGlMQ0pwWkNJNkltWmtNamRqTW1FMExXTTFNVEV0TkRrd01DMWhOamN5TFRoak5UTTFNVEkyWWpnellTSXNJbk4xWWlJNkltRnpkbVZzWlhwbGNrQm5iV0ZwYkM1amIyMGlMQ0pwWVhRaU9qRTNNRFkyTXpNeE5qSXNJbVY0Y0NJNk1UY3dOall6TkRrMk1uMC5JcVc3MGxSWXQxU3l1TW54Ti1kYnlKMHZLem50QU0zcXpzYURKUk1Ub0tzIiwiaWF0IjoxNzA2NjMzMTYyLCJleHAiOjE3MDY2MzQ5NjJ9.hcnnEabs0FTOJqtUh7iX7rTyFAzXsw7Sry-Cjy2SnHY"
}
###
@token=eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFzdmVsZXplckBnbWFpbC5jb20iLCJpZCI6ImZkMjdjMmE0LWM1MTEtNDkwMC1hNjcyLThjNTM1MTI2YjgzYSIsInN1YiI6ImFzdmVsZXplckBnbWFpbC5jb20iLCJpYXQiOjE3MDY2MzMxNjIsImV4cCI6MTcwNjYzNDk2Mn0.IqW70lRYt1SyuMnxN-dbyJ0vKzntAM3qzsaDJRMToKs
###
POST {{baseUrl}}/api/v1/otp HTTP/1.1
Content-Type: application/json

{
    "email": "{{email}}",
    "type": "RESET_PASSWORD"
}
###
@otpIdReset=297391f6-483e-459d-bfa8-2517755d13a6
@otpValueReset=1542
###
PATCH {{baseUrl}}/api/v1/auth/reset HTTP/1.1
Content-Type: application/json

{
    "otpId": "{{otpIdReset}}",
    "otpValue": "{{otpValueReset}}",
    "email": "{{email}}",
    "password": "password"
}
###
###

###
GET {{baseUrl}}/api/v1/user/me HTTP/1.1
Authorization: Bearer {{token}}
###
GET {{baseUrl}}/api/v1/user/me/creditCard HTTP/1.1
Authorization: Bearer {{token}}
###
@creditCardId=d11691ea-b110-4611-8355-a93bf2243394
###
PUT {{baseUrl}}/api/v1/user/me HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name":"name",
    "password": "password"
}
###
GET {{baseUrl}}/api/v1/product HTTP/1.1
###
GET {{baseUrl}}/api/v1/subscription HTTP/1.1
Authorization: Bearer {{token}}
###
@productId=da44debc-c72c-4b77-ac4b-6424bed81f17
# @productId=cb55debc-c72c-4b77-ac4b-6424bed81f11
###
POST {{baseUrl}}/api/v1/subscription HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "productId": "{{productId}}"
}
###
GET {{baseUrl}}/api/v1/subscription HTTP/1.1
Authorization: Bearer {{token}}
###
@subscriptionId=eb57e743-7d38-4fa8-b4ed-6a791d8c52cd
###
PATCH {{baseUrl}}/api/v1/subscription/{{subscriptionId}} HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "qty": 5
}
###
DELETE {{baseUrl}}/api/v1/subscription/{{subscriptionId}} HTTP/1.1
Authorization: Bearer {{token}}
###
GET {{baseUrl}}/api/v1/payment/transaction/history HTTP/1.1
Authorization: Bearer {{token}}
###
POST {{baseUrl}}/api/v1/payment/transaction/history HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "subscriptionId": "{{subscriptionId}}",
    "creditCardId": "{{creditCardId}}",
    "creditCardNumber":"13823982",
    "cvv":"123",
    "expiredDate":"09/2025",
    "cardHolderName":"arief"
}
###
GET {{baseUrl}}/api/v1/payment/transaction/history HTTP/1.1
Authorization: Bearer {{token}}
###
POST {{baseUrl}}/api/v1/otp HTTP/1.1
Content-Type: application/json

{
    "email": "{{email}}",
    "type": "PAYMENT"
}
###
@transactionHistoryId=1bb72543-27e4-476f-942f-1ec3566ae732
@otpIdPayment=8638fed3-7a69-4d8f-889f-78bb3ab3e173
@otpValuePayment=7695
###
PATCH {{baseUrl}}/api/v1/payment/transaction/history/{{transactionHistoryId}} HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "otpId": "{{otpIdPayment}}",
    "otpValue": "{{otpValuePayment}}",
    "amount": 2000000
}
###
GET {{baseUrl}}/api/v1/subscription HTTP/1.1
Authorization: Bearer {{token}}